# mysqlを立ち上げる
version: '3'
services:
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: tutorial
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
